spring:
  datasource:
    url: jdbc:mysql://localhost:3306/WSServer
    username: root
    password: daxingyi20070515
#  jpa:
#    show-sql: true
#    properties:
#      hibernate:
#        forat_sql: true
server:
  port: 8888

eureka:
  client:
    register-with-eureka: false # 是否注册自己的信息到EurekaServer，默认是true
    fetch-registry: false # 是否拉取其它服务的信息，默认是true
    service-url: # EurekaServer的地址，现在是自己的地址，如果是集群，需要加上其它Server的地址。
      defaultZone: http://127.0.0.1:8888/eureka
mybatis:
  type-aliases-package: com.wjr.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
